name: 'Optic Changelog'
description: |
  Generate a changelog for your Optic spec
author: 'Optic'
inputs:
  GITHUB_TOKEN:
    required: true
    description: 'GitHub token'
  OPTIC_SPEC_PATH:
    required: false
    description: |
      File location relative to root for the Optic spec file.
    default: .optic/api/specification.json
  OPTIC_API_KEY:
    required: false
    description: |
      API key generated on https://app.useoptic.com.
    default: ""
  SUBSCRIBERS:
    required: false
    description: |
      GitHub usernames to notify on API changes, comma seperated
    default: ""
runs:
  using: 'node12'
  main: 'dist/index.js'
