name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  GITHUB_TOKEN:
    required: true
    description: 'GitHub token'
  OPTIC_SPEC_PATH:
    required: false
    description: |
      File location relative to root for the Optic spec file.
    default: .optic/api/specification.json
  SUBSCRIBERS:
    required: false
    description: |
      GitHub usernames to notify on API changes, comma seperated
    default: ""
runs:
  using: 'node12'
  main: 'dist/index.js'
